### ISSUE TITLE
Upload Back-End API

### ISSUE THREAD

**Issue by HanHan233** [M4TEC/PenguinPlayer#11]
Upload used PHP Back-End apis so that we could build up our own api

**Comment by LuoTR** [comment]
There is no PHP backend.

**Comment by LuoTR** [comment]
This player uses the service that original should be provided for only [Cloud Music for Garry's Mod](https://github.com/M4TEC/CloudMusicGMOD). But due to my time is very strict, so I can only use this existing service instead make a new one.
