### ISSUE TITLE
进度条控件加载时间过长

### ISSUE THREAD

**Issue by yuezhenglingluan** [M4TEC/PenguinPlayer#13]
进度条加载的时间过长，打开https://m4tec.github.io/PenguinPlayer/demo.html 后好久才出现

**Comment by LuoTR** [comment]
无法重现此问题，Slider类按理来说是不会消耗过长时间进行实例化的

**Comment by LuoTR** [comment]
此问题可能是由于API的Access-Control缓存导致的，目前暂关闭Issue
