### ISSUE TITLE
Deadly performance issue on mobile devices when using a large playlist

### ISSUE THREAD

**Issue by yuezhenglingluan** [M4TEC/PenguinPlayer#16]
Cannot interact with the UI to start playing/stop playing/get the next song that is going to come up.

Edge version 40.15254.603.0
EdgeHTML 15.15254

**Comment by LuoTR** [comment]
[Profile-20210330T004250.zip](https://github.com/M4TEC/PenguinPlayer/files/6223207/Profile-20210330T004250.zip)
No idea about profile analyzing... Attached profile file

**Comment by LuoTR** [comment]
Fixed in recent commits..? Close now, reopen when this issue is found again.
