### ISSUE TITLE
UI 问题：播放列表中最后一首歌曲信息显示不全

### ISSUE THREAD

**Issue by leostudiooo** [M4TEC/PenguinPlayer#27]
如图。

![image](https://user-images.githubusercontent.com/35419343/122003423-a7b82480-cde5-11eb-95bc-041bc123c84a.png)

在移动端播放列表中（以 def 歌单为例）最后一首歌曲的信息显示不全（此处为《START:DASH!!》）。

而在 PC 端则不存在这个问题。

![image](https://user-images.githubusercontent.com/35419343/122003782-185f4100-cde6-11eb-8cb3-0fb7d4542f06.png)

**Comment by LuoTR** [comment]
滚动条插件已知问题，此问题曾出现在歌词全览中，将会使用占位元素进行替代修复
